[pytest]
addopts =
   --browser_name=chromium
    --region=Test
    -v
    -s
    -n 3
    --headed
    --capture=tee-sys
    --dist=loadfile


testpaths =
    TestCases/ProfilePage_testcases

markers =
    serial: tests that must not run in parallel
    user1: run with User1(Dinesh Aravinth)
    user2: run with User2(Nalina)
    user3: run with User3(karthik)
    user4: run with User4(Nethaji)
    user5: run with User5(Thilagam)
    user6: run with User6(Karthik_2)
    user11: run with User11(DineshAravinth---Workflowtemplates)

filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::ResourceWarning
    ignore::ImportWarning
    ignore::UserWarning
    ignore::pytest.PytestDeprecationWarning